<h2> Music </h2>

<div class="container-fluid">
    <div class="row row-cols-2">
        <!-- Headache -->
        <iframe class="col my-2" width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1058862850&color=%231c1c1c&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/user-463322103" title="Gann4Life" target="_blank" style="color: #cccccc; text-decoration: none;">Gann4Life</a> · <a href="https://soundcloud.com/user-463322103/headache" title="Headache" target="_blank" style="color: #cccccc; text-decoration: none;">Headache</a></div>
        <!-- The BeatMaker -->
        <iframe class="col my-2" width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1031220475&color=%231c1c1c&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/user-463322103" title="Gann4Life" target="_blank" style="color: #cccccc; text-decoration: none;">Gann4Life</a> · <a href="https://soundcloud.com/user-463322103/tbm" title="T.B.M" target="_blank" style="color: #cccccc; text-decoration: none;">T.B.M</a></div>
        <!-- The 3rd Dimension -->
        <iframe class="col my-2" width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/951521347&color=%231c1c1c&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/user-463322103" title="Gann4Life" target="_blank" style="color: #cccccc; text-decoration: none;">Gann4Life</a> · <a href="https://soundcloud.com/user-463322103/thirdym" title="The 3rd Dimension" target="_blank" style="color: #cccccc; text-decoration: none;">The 3rd Dimension</a></div>
        <!-- Life Cycle -->
        <iframe class="col my-2" width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/951518605&color=%231c1c1c&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/user-463322103" title="Gann4Life" target="_blank" style="color: #cccccc; text-decoration: none;">Gann4Life</a> · <a href="https://soundcloud.com/user-463322103/life-cycle" title="Life Cycle" target="_blank" style="color: #cccccc; text-decoration: none;">Life Cycle</a></div>
    </div>
</div>