<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php include "templates/general-imports.php" ?>
    <title>Art</title>
</head>
<body>
    <?php
        include "templates/header.php";
    ?>

    <div class="content centered">
        <h1 class="content-title">Art</h1>
        <h2>What do i do?</h2>
        <p>I do different types of art, which includes digital art, animation, motion graph and video editing.</p>
        <br>
        <p>I'll leave the places where you can see all of my content. :)</p>

        <div class="art-content centered">
            <h2 style="padding-right: 25px">See:</h2>
            <a href="https://deviantart.com/gann4life" class="nav-button">DeviantArt</a>
            <a href="https://twitter.com/gann4life" class="nav-button">Twitter</a>
            <a href="https://youtube.com/gann4life" class="nav-button">Youtube</a>
            <a href="https://discord.gg/8USgTyxkKZ" class="nav-button">Join my discord server!</a>
        </div>
        <!--
        <div class="art-content">
            <blockquote class="twitter-tweet art-item"><p lang="en" dir="ltr">Experimenting with some stuff... :D<br>Rendered with DAZ Studio and used some PDN filters. :S<a href="https://twitter.com/hashtag/art?src=hash&amp;ref_src=twsrc%5Etfw">#art</a> <a href="https://twitter.com/hashtag/3dart?src=hash&amp;ref_src=twsrc%5Etfw">#3dart</a> <a href="https://twitter.com/hashtag/3D?src=hash&amp;ref_src=twsrc%5Etfw">#3D</a> <a href="https://twitter.com/hashtag/ArtistOnTwitter?src=hash&amp;ref_src=twsrc%5Etfw">#ArtistOnTwitter</a> <a href="https://twitter.com/hashtag/digitalart?src=hash&amp;ref_src=twsrc%5Etfw">#digitalart</a> <a href="https://twitter.com/hashtag/digitalillustration?src=hash&amp;ref_src=twsrc%5Etfw">#digitalillustration</a> <a href="https://t.co/u1QND36UKf">pic.twitter.com/u1QND36UKf</a></p>&mdash; Gann4Life (@Gann4Life) <a href="https://twitter.com/Gann4Life/status/1347384516588036097?ref_src=twsrc%5Etfw">January 8, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            <blockquote class="twitter-tweet art-item"><p lang="en" dir="ltr">I have made my first commission for a friend, painted in <a href="https://twitter.com/clipstudiopaint?ref_src=twsrc%5Etfw">@clipstudiopaint</a> with the help of <a href="https://twitter.com/hashtag/Blender3d?src=hash&amp;ref_src=twsrc%5Etfw">#Blender3d</a> <br>Final version doesn&#39;t contain the watermark.<a href="https://twitter.com/hashtag/digitalart?src=hash&amp;ref_src=twsrc%5Etfw">#digitalart</a> <a href="https://twitter.com/hashtag/ArtistOnTwitter?src=hash&amp;ref_src=twsrc%5Etfw">#ArtistOnTwitter</a> <a href="https://twitter.com/hashtag/Commission?src=hash&amp;ref_src=twsrc%5Etfw">#Commission</a> <a href="https://twitter.com/hashtag/Logo?src=hash&amp;ref_src=twsrc%5Etfw">#Logo</a> <a href="https://twitter.com/hashtag/LogoDesign?src=hash&amp;ref_src=twsrc%5Etfw">#LogoDesign</a> <a href="https://twitter.com/hashtag/art?src=hash&amp;ref_src=twsrc%5Etfw">#art</a> <a href="https://twitter.com/hashtag/DigitalArtist?src=hash&amp;ref_src=twsrc%5Etfw">#DigitalArtist</a> <a href="https://twitter.com/hashtag/digitalarts?src=hash&amp;ref_src=twsrc%5Etfw">#digitalarts</a> <a href="https://t.co/8wXb5DZmc3">pic.twitter.com/8wXb5DZmc3</a></p>&mdash; Gann4Life (@Gann4Life) <a href="https://twitter.com/Gann4Life/status/1342993964819951616?ref_src=twsrc%5Etfw">December 27, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            <blockquote class="twitter-tweet art-item"><p lang="en" dir="ltr">Not my idea, i swear <a href="https://t.co/IO8NqdBiLu">pic.twitter.com/IO8NqdBiLu</a></p>&mdash; Gann4Life (@Gann4Life) <a href="https://twitter.com/Gann4Life/status/1339363868787785731?ref_src=twsrc%5Etfw">December 17, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            <blockquote class="twitter-tweet art-item"><p lang="en" dir="ltr">I&#39;ve been away from home, so i decided to try out krita and made this random thing... :T<a href="https://twitter.com/hashtag/ArtistOnTwitter?src=hash&amp;ref_src=twsrc%5Etfw">#ArtistOnTwitter</a> <a href="https://twitter.com/hashtag/DigitalArtist?src=hash&amp;ref_src=twsrc%5Etfw">#DigitalArtist</a> <a href="https://twitter.com/hashtag/digitaldrawing?src=hash&amp;ref_src=twsrc%5Etfw">#digitaldrawing</a> <a href="https://twitter.com/hashtag/krita?src=hash&amp;ref_src=twsrc%5Etfw">#krita</a> <a href="https://twitter.com/hashtag/kritaart?src=hash&amp;ref_src=twsrc%5Etfw">#kritaart</a> <a href="https://twitter.com/hashtag/digitalartwork?src=hash&amp;ref_src=twsrc%5Etfw">#digitalartwork</a> <a href="https://twitter.com/hashtag/digitalarts?src=hash&amp;ref_src=twsrc%5Etfw">#digitalarts</a> <a href="https://t.co/EyeW9Ky1LA">pic.twitter.com/EyeW9Ky1LA</a></p>&mdash; Gann4Life (@Gann4Life) <a href="https://twitter.com/Gann4Life/status/1336804954074451969?ref_src=twsrc%5Etfw">December 9, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            <blockquote class="twitter-tweet art-item"><p lang="en" dir="ltr">This time i&#39;ve drawn Hattori, from <a href="https://twitter.com/Brawlhalla?ref_src=twsrc%5Etfw">@Brawlhalla</a> c:<a href="https://twitter.com/hashtag/Brawlhalla?src=hash&amp;ref_src=twsrc%5Etfw">#Brawlhalla</a> <a href="https://twitter.com/hashtag/BrawlhallaArt?src=hash&amp;ref_src=twsrc%5Etfw">#BrawlhallaArt</a> <a href="https://twitter.com/hashtag/digitalart?src=hash&amp;ref_src=twsrc%5Etfw">#digitalart</a> <a href="https://twitter.com/hashtag/ArtistOnTwitter?src=hash&amp;ref_src=twsrc%5Etfw">#ArtistOnTwitter</a> <a href="https://twitter.com/hashtag/digitalartwork?src=hash&amp;ref_src=twsrc%5Etfw">#digitalartwork</a> <a href="https://t.co/nCQq2kNiAk">pic.twitter.com/nCQq2kNiAk</a></p>&mdash; Gann4Life (@Gann4Life) <a href="https://twitter.com/Gann4Life/status/1296501116188983296?ref_src=twsrc%5Etfw">August 20, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            <blockquote class="twitter-tweet art-item"><p lang="en" dir="ltr">I just drew Scarlet from <a href="https://twitter.com/Brawlhalla?ref_src=twsrc%5Etfw">@Brawlhalla</a> :]<a href="https://twitter.com/hashtag/Brawlhalla?src=hash&amp;ref_src=twsrc%5Etfw">#Brawlhalla</a> <a href="https://twitter.com/hashtag/BrawlhallaArt?src=hash&amp;ref_src=twsrc%5Etfw">#BrawlhallaArt</a> <a href="https://twitter.com/hashtag/digitalart?src=hash&amp;ref_src=twsrc%5Etfw">#digitalart</a> <a href="https://twitter.com/hashtag/ArtistOnTwitter?src=hash&amp;ref_src=twsrc%5Etfw">#ArtistOnTwitter</a> <a href="https://twitter.com/hashtag/digitalartwork?src=hash&amp;ref_src=twsrc%5Etfw">#digitalartwork</a> <a href="https://t.co/zLoj7SJ96Z">pic.twitter.com/zLoj7SJ96Z</a></p>&mdash; Gann4Life (@Gann4Life) <a href="https://twitter.com/Gann4Life/status/1295866556589711360?ref_src=twsrc%5Etfw">August 18, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            <blockquote class="twitter-tweet art-item"><p lang="en" dir="ltr">Tried my best there on drawing <a href="https://twitter.com/mikeshinoda?ref_src=twsrc%5Etfw">@mikeshinoda</a> there. :)<a href="https://twitter.com/hashtag/digitalart?src=hash&amp;ref_src=twsrc%5Etfw">#digitalart</a> <a href="https://twitter.com/hashtag/digitalartwork?src=hash&amp;ref_src=twsrc%5Etfw">#digitalartwork</a> <a href="https://twitter.com/hashtag/digitaldrawing?src=hash&amp;ref_src=twsrc%5Etfw">#digitaldrawing</a> <a href="https://twitter.com/hashtag/artistontwitter?src=hash&amp;ref_src=twsrc%5Etfw">#artistontwitter</a> <a href="https://twitter.com/hashtag/digital?src=hash&amp;ref_src=twsrc%5Etfw">#digital</a> <a href="https://twitter.com/hashtag/fanart?src=hash&amp;ref_src=twsrc%5Etfw">#fanart</a> <a href="https://t.co/Kq8JkSLs4r">pic.twitter.com/Kq8JkSLs4r</a></p>&mdash; Gann4Life (@Gann4Life) <a href="https://twitter.com/Gann4Life/status/1279754935433924609?ref_src=twsrc%5Etfw">July 5, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            <blockquote class="twitter-tweet art-item"><p lang="en" dir="ltr">I&#39;ve re-drawn some old art i&#39;ve made! :D<a href="https://twitter.com/hashtag/digitalart?src=hash&amp;ref_src=twsrc%5Etfw">#digitalart</a> <a href="https://twitter.com/hashtag/digitalartwork?src=hash&amp;ref_src=twsrc%5Etfw">#digitalartwork</a> <a href="https://twitter.com/hashtag/digitaldrawing?src=hash&amp;ref_src=twsrc%5Etfw">#digitaldrawing</a> <a href="https://twitter.com/hashtag/artistsontwitter?src=hash&amp;ref_src=twsrc%5Etfw">#artistsontwitter</a> <a href="https://twitter.com/hashtag/ArtistOnTwitter?src=hash&amp;ref_src=twsrc%5Etfw">#ArtistOnTwitter</a> <a href="https://twitter.com/hashtag/digital?src=hash&amp;ref_src=twsrc%5Etfw">#digital</a> <a href="https://twitter.com/hashtag/originalart?src=hash&amp;ref_src=twsrc%5Etfw">#originalart</a> <a href="https://twitter.com/hashtag/originalartwork?src=hash&amp;ref_src=twsrc%5Etfw">#originalartwork</a> <a href="https://t.co/SKAMnvtdr1">pic.twitter.com/SKAMnvtdr1</a></p>&mdash; Gann4Life (@Gann4Life) <a href="https://twitter.com/Gann4Life/status/1278571275250696193?ref_src=twsrc%5Etfw">July 2, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            <blockquote class="twitter-tweet art-item"><p lang="en" dir="ltr">I&#39;ve made an artwork for an amazing Plazma Burst fan, @dev_cmd_deb :)<a href="https://twitter.com/PlazmaBurstTeam?ref_src=twsrc%5Etfw">@PlazmaBurstTeam</a> <a href="https://twitter.com/Eric_Gurt?ref_src=twsrc%5Etfw">@Eric_Gurt</a> <a href="https://twitter.com/hashtag/plazmaburst?src=hash&amp;ref_src=twsrc%5Etfw">#plazmaburst</a> <a href="https://t.co/tlZauBex4b">pic.twitter.com/tlZauBex4b</a></p>&mdash; Gann4Life (@Gann4Life) <a href="https://twitter.com/Gann4Life/status/1248699500266500098?ref_src=twsrc%5Etfw">April 10, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            <blockquote class="twitter-tweet art-item"><p lang="en" dir="ltr">It works :D<br>14:54 <a href="https://t.co/S04GANYBrO">pic.twitter.com/S04GANYBrO</a></p>&mdash; Gann4Life (@Gann4Life) <a href="https://twitter.com/Gann4Life/status/1080160609021411328?ref_src=twsrc%5Etfw">January 1, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            <blockquote class="twitter-tweet art-item"><p lang="und" dir="ltr">Huh?<br><br>03:39 <a href="https://t.co/pIzFg5ky8P">pic.twitter.com/pIzFg5ky8P</a></p>&mdash; Gann4Life (@Gann4Life) <a href="https://twitter.com/Gann4Life/status/1079990799897690112?ref_src=twsrc%5Etfw">January 1, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div> 
        -->
    </div>

    <!-- This file is supposed to use the 'digitalart' folder, for loading pictures, descriptions, or whatever -->
    <?php include "templates/footer.php"; ?>
</body>
</html>